services:

  adguard:
    container_name: "adguard"
    image: "adguard/adguardhome:latest"
    ports:
      - "53:53/udp"
      - "3000:3000"
    volumes:
      - "/srv/adguard/work/:/opt/adguardhome/work/"
      - "/srv/adguard/conf/:/opt/adguardhome/conf/"
    restart: "unless-stopped"
    networks:
      mauri-net:
        ipv4_address: "10.100.0.100"

  wireguard:
    container_name: "wireguard"
    image: "weejewel/wg-easy:latest"
    ports:
      - "23:51820/udp"
    volumes:
      - "/srv/wireguard/:/etc/wireguard/"
    cap_add:
      - "NET_ADMIN"
      - "SYS_MODULE"
    environment:
      WG_HOST: "${SRV_DUCKDNS_SUBDOMAIN}.duckdns.org"
      WG_PORT: "23"
      WG_DEFAULT_DNS: "10.100.0.100"
      PASSWORD: "${SRV_ADMIN_PASSWORD}"
    privileged: true
    restart: "unless-stopped"
    depends_on:
      - "adguard"
    networks:
      mauri-net:
        ipv4_address: "10.100.0.101"

  nginx-ssl:
    container_name: "nginx-ssl"
    image: "nginx:latest"
    ports:
      - "443:443"
    volumes:
      - "/srv/nginx/conf/main.nginx.conf:/etc/nginx/nginx.conf"
      - "/srv/nginx/certbot/conf:/etc/letsencrypt"
    restart: "unless-stopped"
    depends_on:
      - adguard
      - emby
      - filebrowser
      - nginx
    networks:
      mauri-net:
        ipv4_address: "10.100.0.102"

  spigot:
    container_name: "spigot"
    image: "nimmis/spigot:latest"
    ports:
      - "25565:25565"
    environment:
      EULA: "true"
      SPIGOT_VER: "1.19.3"
      MC_MAXMEM: "8g"
      MC_MINMEM: "3g"
    restart: "unless-stopped"
    volumes:
      - "/srv/spigot:/minecraft"
    networks:
      mauri-net:
        ipv4_address: "10.100.0.103"

  duckdns:
    container_name: "duckdns"
    image: "linuxserver/duckdns:latest"
    environment:
      TZ: "America/Santiago"
      SUBDOMAINS: "${SRV_DUCKDNS_SUBDOMAIN}"
      TOKEN: "${SRV_DUCKDNS_TOKEN}"
    restart: "unless-stopped"
    networks:
      mauri-net:
        ipv4_address: "10.100.0.104"

  emby:
    container_name: "emby"
    image: "emby/embyserver"
    ports:
      - "8096:8096/tcp"
    environment:
      TZ: "America/Santiago"
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - "/srv/plex/config:/config"
      - "/external/Media/Shows:/mnt/shows"
      - "/external/Media/Movies:/mnt/movies"
      - "/external/Media/Music:/mnt/music"
    restart: "unless-stopped"
    networks:
      mauri-net:
        ipv4_address: "10.100.0.105"

  filebrowser:
    container_name: "filebrowser"
    image: "filebrowser/filebrowser:s6"
    ports:
      - "8080:80"
    volumes:
      - "/srv/filebrowser/database:/database"
      - "/srv/filebrowser/config:/config"
      - "/srv/filebrowser/media:/srv"
      - "/external/Media:/srv/Shared/Emby Library" # << use ln -sf inside filebrowser in order to act as a shared folder!
    restart: "unless-stopped"
    networks:
      mauri-net:
        ipv4_address: "10.100.0.106"

  nginx:
    container_name: "nginx"
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - "/srv/nginx/conf/certbot.nginx.conf:/etc/nginx/nginx.conf"
      - "/srv/nginx/certbot/conf:/etc/letsencrypt"
      - "/srv/nginx/certbot/www:/var/www/certbot"
    restart: "unless-stopped"
    networks:
      mauri-net:
        ipv4_address: "10.100.0.107"

  palworld:
    container_name: "palworld"
    image: "thijsvanloef/palworld-server-docker:latest"
    ports:
      - "8211:8211/udp"
      - "27015:27015/udp"
    environment:
      PUID: 1000
      PGID: 1000
      PORT: 8211
      PLAYERS: 8
      SERVER_PASSWORD: "passwordcilla"
      MULTITHREADING: "true"
      RCON_ENABLED: "true"
      RCON_PORT: 25575
      TZ: "America/Santiago"
      ADMIN_PASSWORD: "${SRV_ADMIN_PASSWORD}"
      COMMUNITY: "false"
      SERVER_NAME: "MauriLand"
      SERVER_DESCRIPTION: "Bienvenid@s a MauriLand!"
    volumes:
      - "/srv/palworld:/palworld"
    restart: "unless-stopped"
    networks:
      mauri-net:
        ipv4_address: "10.100.0.108"

networks:
  mauri-net:
    name: "mauri-net"
    ipam:
      config:
        - subnet: "10.100.0.0/24"